#!/usr/bin/env bash
set -Eeuo pipefail

if [[ "${PILOT_TEST_MODE:-0}" == "1" ]]; then
  install_dir="${PILOT_INSTALL_DIR:?PILOT_INSTALL_DIR fehlt im Testmodus}"
  workdir="${PILOT_WORKDIR:?PILOT_WORKDIR fehlt im Testmodus}"
else
  install_dir="/opt/labforge/kapitel-02-killercoda-pilot"
  workdir="/home/telegrafist/nachtstation"
fi

exec /usr/bin/python3 -I \
  "$install_dir/interne-skripte/config_parser.py" \
  --config "$workdir/leitung-zwei/xebico.conf" \
  --base-dir "$workdir"
